name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # Se actualiza cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Stats
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=jelujr17&count_private=true&include_all_commits=true&show_icons=true&theme=dracula&token=$GH_STATS_TOKEN"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=jelujr17&count_private=true&layout=compact&theme=dracula&token=$GH_STATS_TOKEN"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add stats.svg langs.svg
          git commit -m "Updated GitHub Stats" || echo "No changes to commit"
          git push
